### ISSUE TITLE
NOAUTH Authentication required

### ISSUE THREAD

**Issue by antoniosilva000000** [adonisjs/redis#47]
I seem to have installed and configured Redis correctly as specified, but whenever I try to use some redis command I get this error message: "NOAUTH Authentication required.".
I'm using --requirepass and even setting the 'password' property on the local connection in config redis I'm still "NOAUTH". What to do?

_redis.ts_
```
...
connection: Env.get('REDIS_CONNECTION'),
connections: {
   local: {
      host: Env.get('REDIS_HOST'),
      port: Env.get('REDIS_PORT'),
      password: Env.get('REDIS_PASSWORD', ''),
      db: 0,
      keyPrefix: 'cache:',
   },
}
```

_.env_
```
REDIS_CONNECTION=local
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=123
```

_docker-compose.yml_
```
services:
   redis:
       image: redis:latest
       restart: always
       command: redis-server --save 60 1 --loglevel warning --requirepass 123
       ports:
         - '6379:6379'
```
